// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const healthCheck = `-- name: HealthCheck :one
SELECT now()::timestamptz AS now
`

// 返回数据库当前时间, 用于演示 sqlc 生成流程并验证连通性.
func (q *Queries) HealthCheck(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, healthCheck)
	var now pgtype.Timestamptz
	err := row.Scan(&now)
	return now, err
}
